### ISSUE TITLE
The bark bundle will switch its type depending on the type used for the last bark

### ISSUE THREAD

**Issue by Teozard** [Aetherial-Labs/InDappledGroves#17]
**Steps to reproduce:**
1. Get 4 barks of a type **A** and 1 bark of type **B**
2. Place four type **A** barks on the ground
3. Create a bundle using the type **B** bark 

**Expected result:**
Was not specified by the dev, but I expect three possible outcome 
1. User may be only able to create a bundle using one type of bark 
2. Bundle will be the type of majority bark used 
3. Mixed bark item 

**Actual result:**
A bundle is created however, every bark is converted to the type B bark, making It possible to magically change the type of bark the user use

**Comment by VinterNacht** [comment]
Updated and fixed in 0.4.8
