### ISSUE TITLE
Axes do not respect ICustomTreeFellingBehavior

### ISSUE THREAD

**Issue by noelle-lavenza** [Aetherial-Labs/InDappledGroves#22]
Trees using `ICustomTreeFellingBehavior`, like fern trees, fruit trees, and bamboo, can be chopped with axes but don't fall.

**Comment by VinterNacht** [comment]
Thank you for this.  Will investigate and resolve.

**Comment by VinterNacht** [comment]
Sorry about the long delay here.  Will put it on my list of things to deal with as I get back in the saddle this week.

**Comment by VinterNacht** [comment]
Corrected in unreleased v0.4.8.
