### ISSUE TITLE
Wood slabs do not reliably chop into firewood

### ISSUE THREAD

**Issue by TheOringalIntreeg** [Aetherial-Labs/InDappledGroves#28]
When chopping wood slabs on a chopping block, I noted the following behaviors...
1. 1 in 2 to 1 in 5 (random) times the chopping wood slabs works on the first go. I'm using a stone ax. I also noticed the issue tends to be more likely with the second wood slab after chopping a log.
2. When it does not work the slab will disappear, the space will be traversable. When another slab is placed, the inventory count does not change. When a log is placed, a wood slab appears instead. Once the slab is successfully chopped into firewood, a log can be placed on the slab for chopping.

Fixes attempted...
1. Restarting game
2. Disabling all other mods and starting a new world to test error reproducibility (confirmed)

Current Mod List...

animalcages_v2.0.6
AnvilMetalRecover_V0.1.18-RC.2_Debug
ArrowheadsRecovery_v1.0.1
CarryOn-1.17.9_v0.10.3
cob_seraphvoices_1.0.0
cob_tradercamps_1.0.4
ExpandedFoods 1.6.4
FeverstoneHorses-v1.3.9-rc.2-1.17.x
frozenreedsmod
glassmaking_v1.3.3
hangingoillamps_1.0.1
InDappledGroves-1.17-v0.4.7
instruments_1.1.4
medievalexpansion-3.8.1
MeteoricExpansion_V1.2.2
MeteoricExpansion_V1.2.2
MoreClay-1.0.1
MoreRoads 1.5.1
OresAPlenty_v3.0.0
PlayerCorpse_v1.17.9_v1.5.5
PrimitiveSurvival3.1.1
qptech1.12.26
RainCollector-v1.0.0
TeleportationNetwork_v1.17.9_v1.8.0-rc.1
UsefulDrifterLoot 1.0.1
VisibleOre
vsvillage_v0.5.0

**Comment by TheOringalIntreeg** [comment]
Love this mod. Has great potential. Going to attempt to assist with debugging. Starting with assets/indappledgroves/blocktypes/barkbasket.json because it is on the top of the list. Will post for review when done.

**Comment by TheOringalIntreeg** [comment]
Went a bit overboard with debugging. See attached files for review. 
[Debuged Files.zip](https://github.com/Aetherial-Labs/InDappledGroves/files/10421709/Debuged.Files.zip)
Mostly ran into "Property keys must be doublequoted" errors and a few trailing commas.

**Comment by VinterNacht** [comment]
LOL...

The property keys and such aren't really errors... Newtonsoft.json is perfectly happy with them.  That's just the default Visual Studio approach. You'll see those in every mod (Especially mod of mine) because I've learned to ignore them.

**Comment by VinterNacht** [comment]
But it's *much* less annoying to have them "not present"

**Comment by TheOringalIntreeg** [comment]
Alright. As long as it is helping, I will continue my efforts then.

**Comment by TheOringalIntreeg** [comment]
And done. See attached. Will test it now.
[InDappledGroves - Debugged.zip](https://github.com/Aetherial-Labs/InDappledGroves/files/10425933/InDappledGroves.-.Debugged.zip)

**Comment by TheOringalIntreeg** [comment]
Alright. This morning, chopping wood blocks is working well. Unfortunately now sticks have no texture and are represented by white 2d squares. They can also not be crafted with. All I have really done is restart my computer and update my GFX driver.

**Comment by TheOringalIntreeg** [comment]
I sort of  figured out what was going on.
1. Some bug deleted the file for stick in the VS vanilla files.
2. Dependencies were missing for FeverstoneHorses-v1.3.9-rc.2-1.17.x, MoreRoads 1.5.1, ExpandedFoods 1.6.4
3. Had a feeling Carryon was causing an issue.

Solution: Uninstalled those mods, reinstalled VS (which updated it, to my chagrin)

Now chopping is working, sticks are showing up, and the game is working perfectly. Sorry for any undue troubleshooting but will leave this comment so others don't have run through the same mistakes. Turns out this issue was affecting Layer 8 of the OSI model LOL (operator error).

**Comment by TheOringalIntreeg** [comment]
See above comment for closing details.
